---
title: "Linear Models"
output: github_document
---

```{r setting up R markdown}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis", 
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

#Problem 1

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    borough = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(borough != "Staten Island") %>%
  #filer out Staten Isalnd
  select(price, stars, borough, neighborhood, room_type)
```

## Fit a model 

Star rating for borough?

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = borough)) + 
  geom_point()
```


```{r}
fit = lm(price ~ stars + borough, data = nyc_airbnb)
```

lets look at result 

```{r, include = FALSE}
fit

summary(fit)
coefficients(fit)
residuals(fit)
```

Let's look at results better

```{r}
broom::glance(fit)

broom::tidy(fit) %>% 
  select(-std.error, -statistic) %>% 
  mutate(
    term = str_replace(term, "borough", "Borough: ")
    ) %>% 
  knitr::kable()
```

